export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const FAVOURITES_ROUTE = '/favourites'
export const COURSE_ROUTE = '/course'
export const USER_ROUTE = '/user'
export const CONTACT_ROUTE = '/styles'

export const CERTIFICATE_ROUTE = '/certificates'
export const MASTER_ROUTE = '/master-panel'
export const CREATING_ROUTE = '/creating-course'
export const CREATING_WRITE_ROUTE = '/creating-write'